# This is a basic workflow to help you get started with Actions

name: Deploy with surge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install NodeJS
      - name: Install NodeJS
        run: actions/setup-node@v2-beta
      
      # Install yarn
      - name: Install yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # performs yarn install
      
      # Build react-app
      - name: Build React App with yarn
        run: yarn build
      
      # Install Surge
      - name: Install Surge
        run: npm install --global surge
      
      # Deploy react app with surge
      - name: deploy react app with surge
        run: surge ./build react-one-1.surge.sh --token ${{ secrets.SURGE_TOKEN }}
